import { useEffect, useState } from "react";
import { CalendarDays, Save, Trash2, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiMessage, apiRequest } from "../api";

const EMPTY_EVENT = { title: "", description: "", eventDate: "", location: "", active: true };

export default function ClubPage() {
  const [content, setContent] = useState(null);
  const [settings, setSettings] = useState({ active: true, title: "", intro: "", benefits: "" });
  const [event, setEvent] = useState(EMPTY_EVENT);
  const [state, setState] = useState("loading");
  const [alert, setAlert] = useState(null);
  const load = async () => { try { const payload = await apiRequest("/admin/pasta-lover-club"); setContent(payload); setSettings(payload.settings); setState("ready"); } catch (error) { setAlert({ kind: "error", message: apiMessage(error, "Impossible de charger le club.") }); setState("error"); } };
  useEffect(() => { load(); }, []);
  async function saveSettings(e) { e.preventDefault(); try { const payload = await apiRequest("/admin/pasta-lover-club", { method: "PUT", body: JSON.stringify(settings) }); setContent(payload); setSettings(payload.settings); setAlert({ kind: "success", message: "Présentation du club enregistrée." }); } catch (error) { setAlert({ kind: "error", message: apiMessage(error) }); } }
  async function addEvent(e) { e.preventDefault(); try { await apiRequest("/admin/pasta-lover-club/events", { method: "POST", body: JSON.stringify(event) }); setEvent(EMPTY_EVENT); await load(); setAlert({ kind: "success", message: "Rendez-vous ajouté." }); } catch (error) { setAlert({ kind: "error", message: apiMessage(error) }); } }
  async function deleteEvent(id) { try { await apiRequest(`/admin/pasta-lover-club/events/${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); setAlert({ kind: "success", message: "Rendez-vous supprimé." }); } catch (error) { setAlert({ kind: "error", message: apiMessage(error) }); } }
  if (state === "loading") return <p className="bo-empty">Chargement…</p>;
  return <div className="bo-club-page"><div className="bo-panel-heading"><div><p className="bo-eyebrow">Communauté</p><h2>Pasta Lover Club</h2><p className="bo-page-intro">Gérez la présentation du club, ses rencontres, ses soirées et ses produits de communauté.</p></div><UsersRound size={24} strokeWidth={1.5} /></div>{alert && <p className="bo-alert" data-kind={alert.kind} role="status">{alert.message}</p>}<form className="bo-club-settings" onSubmit={saveSettings}><div className="bo-club-section-title"><div><p className="bo-eyebrow">Page publique</p><h3>Présentation</h3></div><label className="bo-schedule-switch"><input type="checkbox" checked={settings.active} onChange={(e) => setSettings((current) => ({ ...current, active: e.target.checked }))} /><span className="bo-schedule-switch-control" aria-hidden="true">✓</span><span>Page active</span></label></div><label>Titre<input value={settings.title} onChange={(e) => setSettings((current) => ({ ...current, title: e.target.value }))} required /></label><label>Introduction<textarea rows="3" value={settings.intro} onChange={(e) => setSettings((current) => ({ ...current, intro: e.target.value }))} required /></label><label>Rendez-vous et avantages<textarea rows="5" value={settings.benefits} onChange={(e) => setSettings((current) => ({ ...current, benefits: e.target.value }))} placeholder="Un élément par ligne" /></label><Button type="submit"><Save size={14} /> Enregistrer la page</Button></form><section className="bo-club-events"><div className="bo-section-heading"><div><p className="bo-eyebrow">Programmation</p><h3>Rencontres et soirées</h3></div></div><form className="bo-club-event-form" onSubmit={addEvent}><Input placeholder="Nom de l'événement" value={event.title} onChange={(e) => setEvent((current) => ({ ...current, title: e.target.value }))} required /><Input type="date" value={event.eventDate} onChange={(e) => setEvent((current) => ({ ...current, eventDate: e.target.value }))} /><Input placeholder="Lieu" value={event.location} onChange={(e) => setEvent((current) => ({ ...current, location: e.target.value }))} /><Input placeholder="Description" value={event.description} onChange={(e) => setEvent((current) => ({ ...current, description: e.target.value }))} /><Button type="submit"><CalendarDays size={14} /> Ajouter</Button></form>{content?.events?.length ? <div className="bo-club-event-list">{content.events.map((item) => <article className="bo-club-event" key={item.id}><div><strong>{item.title}</strong><small>{item.eventDate || "Date à préciser"}{item.location ? ` · ${item.location}` : ""}</small><p>{item.description}</p></div><Button variant="outline" size="sm" onClick={() => deleteEvent(item.id)} aria-label={`Supprimer ${item.title}`}><Trash2 size={14} /></Button></article>)}</div> : <p className="bo-empty">Aucun rendez-vous programmé.</p>}</section></div>;
}
